name: NuGet Publish

on:
  push:
    tags:
      - "v*.*.*" # Product tags, e.g., 'v1.0.0'
      - "core/v*.*.*" # Core package tags
      - "redis/v*.*.*" # Redis package tags
      - "blob/v*.*.*" # Blob Storage package tags
      - "distributed/v*.*.*" # Distributed Cache package tags
      - "fusion-cache/v*.*.*" # Fusion cache package tags
      - "s3/v*.*.*" # S3 package tags
      - "postgres/v*.*.*" # Postgres package tags

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref_name }}"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      BUILD_TARGET: "" # set below based on tag prefix, e.g., 'LeaderElection.Redis', or 'LeaderElection.slnx' for full product release
      VERSION: "" # set below from tag version, e.g., '1.0.0'

    steps:
      - name: Parse tag
        env:
          TAG_NAME: ${{ github.ref_name }}
        shell: pwsh
        run: |
          # See https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
          $semverCore = '(?<version>(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*))'
          $semverPre = '(?<prerelease>-(?:(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?'
          $semverMeta = '(?<metadata>\+(?:[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?'
          $semver = $semverCore + $semverPre + $semverMeta

          $buildTarget = switch -Regex ($Env:TAG_NAME) {
            "^core/v$semver`$"         { 'src/LeaderElection' }
            "^redis/v$semver`$"        { 'src/LeaderElection.Redis' }
            "^blob/v$semver`$"         { 'src/LeaderElection.BlobStorage' }
            "^distributed/v$semver`$"  { 'src/LeaderElection.DistributedCache' }
            "^fusion-cache/v$semver`$" { 'src/LeaderElection.FusionCache' }
            "^s3/v$semver`$"           { 'src/LeaderElection.S3' }
            "^postgres/v$semver`$"     { 'src/LeaderElection.Postgres' }
            "^v$semver`$"              { 'LeaderElection.slnx' }
            default                    { throw "Invalid tag: '$_'" }
          }
          $version = $Matches['version'] + $Matches['prerelease'] # ignore metadata
          echo "BUILD_TARGET=$buildTarget" >> $Env:GITHUB_ENV
          echo "VERSION=$version" >> $Env:GITHUB_ENV

      - uses: actions/checkout@v6

      - uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      # Cache NuGet packages to speed up builds
      - uses: actions/cache@v5
        with:
          path: ~/.nuget/packages
          # key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          # We don't use a package lock so we can't key off that, but we can
          # use the hash of all project files to invalidate the cache when
          # dependencies change.
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/Directory.*.props') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Build ${{ env.BUILD_TARGET }}
        run: |
          dotnet build $BUILD_TARGET --no-restore --configuration Release -p:Version=$VERSION

      - name: Package ${{ env.BUILD_TARGET }}
        run: |
          dotnet pack $BUILD_TARGET --no-build --configuration Release -p:Version=$VERSION --output artifacts/package/release

      - name: Push Nuget packages
        run: |
          dotnet nuget push artifacts/package/release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
